### ISSUE TITLE
Strange work with concated streams

### ISSUE THREAD

**Issue by tamtakoe** [teambition/merge2#2]
*Windows, node.js v 0.12.2*

1) for `gulp-merge` (npm link direct to this project).

**Example**

File structure:
<pre>
test1
|- script1.js
|- script2.js
|- ...
test2
...
test5
</pre>

gulpfile.js:
```js
gulp.task('test', function() {
    var streamsArr = [];

    for (var stream, i = 1; i < 5; i++) {
        stream = gulp.src(path.join(__dirname, 'test' + i, '**/*'))
            .pipe(through.obj(function(file, enc, callback) {
                setTimeout(function() {
                    callback(null, file);

                }, Math.ceil(Math.random()*100));
            }))
            .pipe(require('gulp-concat')('script.js'))
            .on('end', (function(i) {
                console.log('end of the stream ' + i);
            }).bind(null, i));

        streamsArr.push(stream);
    }

    require('gulp-merge')(streamsArr)
        .pipe(through.obj(function(file, enc, callback){
            console.log('merged stream transform:', path.relative(__dirname, file.path));

            callback(null, file);

        }, function(callback) {
            console.log('merged stream flush');

            callback();
        }))
        .on('end', function() {
            console.log('end of the merged stream');
        });
});
```
console:
<pre>
end of the stream 4
end of the stream 3
merged stream transform: test1\script.js
end of the stream 1
merged stream transform: test2\script.js
end of the stream 2
</pre>
Somehow, part of a stream is lost. Also did not work flush and `end` event of merged stream.

2) for `merge2` i have
`TypeError: Cannot read property 'endEmitted' of undefined
    at pipe (D:\Projects\test\node_modules\merge2\index.js:57:32) <...>`

**Comment by zensh** [comment]
I have test this code in my Mac with node.js 0.12.2, it work well.

`TypeError: Cannot read property 'endEmitted' of undefined` (stream._readableState.endEmitted) is strange, all readable stream should have `_readableState` property.

There are maybe bug in other codes~

PS: **streams in array will be merged in parallel, not in sequence**

**Comment by zensh** [comment]
And, your last codes:

```
.on('end', function() {
    console.log('end of the merged stream');
});
```

will not run... through stream will be paused

**Comment by tamtakoe** [comment]
There was a problem in the `gulp-concat`. I used v. 2.4.3, but in 2.5.2 it was fixed

Now my test examle works correct, but I use this case in my project and get error
<pre>
D:\Projects\test\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:770
    throw new Error('Cannot switch to old mode now.');
          ^
Error: Cannot switch to old mode now.
    at emitDataEvents (D:\Projects\test\node_modules\through2\node_modules\readable-stream\lib\_stream_readabl
e.js:770:11)
    at DestroyableTransform.Readable.pause (D:\Projects\test\node_modules\through2\node_modules\readable-strea
m\lib\_stream_readable.js:761:3)
    at pauseStreams (D:\Projects\test\node_modules\merge2\index.js:92:13)
    at pauseStreams (D:\Projects\test\node_modules\merge2\index.js:94:57)
    at addStream (D:\Projects\test\node_modules\merge2\index.js:29:25)
    at merge2 (D:\Projects\test\node_modules\merge2\index.js:83:30)
    at DestroyableTransform.flush [as _flush] (D:\Projects\test\lib\compile-modules.js:208:9)
    at DestroyableTransform.<anonymous> (D:\Projects\test\node_modules\through2\node_modules\readable-stream\l
ib\_stream_transform.js:135:12)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:104:17)
</pre>
Unfortunatelly, I can't localize problem. What could it be?

**Comment by zensh** [comment]
I have relase v0.3.4 for compat with old-style streams, it maybe work with you

**Comment by zensh** [comment]
Sorry, the `gulp-merge` is out of date. Please using `merge2`, I have removed `gulp-merge` from npm.
